const PREFIX = "CALENDAR";

const constants = {
  SET_ACTIVE_DAY: `${PREFIX}/SET_ACTIVE_DAY`,
  ADD_REMINDER: `${PREFIX}/ADD_REMINDER`,
  EDIT_REMINDER: `${PREFIX}/EDIT_REMINDER`,
  REMOVE_REMINDER: `${PREFIX}/REMOVE_REMINDER`,
  IS_LOADING_WEATHER: `${PREFIX}/IS_LOADING_WEATHER`,
  IS_LOADING_WEATHER_DONE: `${PREFIX}/IS_LOADING_WEATHER_DONE`,
};

export default constants;
